INDEX_DEFINITIONS = {
    "users": [
        {"keys": [("mobile_number", 1)], "unique": True},
        {"keys": [("email", 1)], "unique": True, "sparse": True},
        {"keys": [("deleted_at", 1)]},
    ],
    "otp_requests": [
        {"keys": [("mobile_number", 1), ("created_at", -1)]},
        {"keys": [("expires_at", 1)], "expireAfterSeconds": 0},
    ],
    "refresh_tokens": [
        {"keys": [("token_hash", 1)], "unique": True},
        {"keys": [("user_id", 1)]},
    ],
    "stations": [
        {"keys": [("location", "2dsphere")]},
        {"keys": [("station_id", 1)], "unique": True},
        {"keys": [("brand", 1), ("city", 1)]},
        {"keys": [("operator_id", 1)]},
        {"keys": [("operational_status", 1)]},
        {"keys": [("verification_status", 1)]},
        {"keys": [("demo_charging_enabled", 1)]},
        {"keys": [("city", 1), ("state", 1)]},
        {"keys": [("demo_charging_enabled", 1), ("operational_status", 1)]},
        {"keys": [("confidence", 1)]},
    ],
    "evses": [
        {"keys": [("evse_id", 1)], "unique": True},
        {"keys": [("station_id", 1)]},
    ],
    "connectors": [
        {"keys": [("connector_id", 1)], "unique": True},
        {"keys": [("evse_id", 1)]},
        {"keys": [("connector_type", 1)]},
        {"keys": [("status", 1)]},
        {"keys": [("demo_charger_id", 1)], "unique": True, "sparse": True},
    ],
    "charging_sessions": [
        {"keys": [("user_id", 1), ("status", 1)]},
        {"keys": [("user_id", 1), ("created_at", -1)]},
        {"keys": [("station_id", 1)]},
        {"keys": [("connector_id", 1)]},
        {"keys": [("status", 1), ("updated_at", -1)]},
        {"keys": [("session_id", 1)], "unique": True},
        {"keys": [("idempotency_key", 1)], "unique": True, "sparse": True},
    ],
    "session_meter_values": [
        {"keys": [("session_id", 1), ("recorded_at", 1)]},
    ],
    "wallet_ledger_entries": [
        {"keys": [("ledger_entry_id", 1)], "unique": True},
        {"keys": [("wallet_id", 1), ("created_at", -1)]},
        {"keys": [("user_id", 1), ("created_at", -1)]},
        {"keys": [("reference_id", 1)], "unique": True},
        {"keys": [("idempotency_key", 1)], "unique": True, "sparse": True},
    ],
    "payments": [
        {"keys": [("payment_id", 1)], "unique": True},
        {"keys": [("user_id", 1), ("created_at", -1)]},
        {"keys": [("status", 1)]},
        {"keys": [("idempotency_key", 1)], "unique": True, "sparse": True},
    ],
    "support_tickets": [
        {"keys": [("user_id", 1), ("created_at", -1)]},
        {"keys": [("status", 1), ("priority", 1)]},
        {"keys": [("ticket_id", 1)], "unique": True},
    ],
}

REQUIRED_COLLECTIONS = [
    "users",
    "otp_requests",
    "refresh_tokens",
    "device_sessions",
    "user_preferences",
    "notification_preferences",
    "vehicles",
    "connector_preferences",
    "providers",
    "operators",
    "stations",
    "evses",
    "connectors",
    "tariffs",
    "tariff_components",
    "station_amenities",
    "station_status_snapshots",
    "station_verification_evidence",
    "charging_sessions",
    "charging_session_events",
    "session_meter_values",
    "wallets",
    "wallet_ledger_entries",
    "payments",
    "payment_events",
    "refunds",
    "invoices",
    "saved_stations",
    "recent_searches",
    "issue_reports",
    "support_tickets",
    "support_messages",
    "notifications",
    "app_config",
    "feature_flags",
    "audit_logs",
    "integration_logs",
    "import_jobs",
    "data_quality_issues",
    "idempotency_records",
]
